export const MAIN_COLOR = "white"
export const ACCENT_COLOR = "#4D4D4D"
export const ACCENT_HOVER = "#323232"
export const OPACITY_BG_COLOR = "rgba(77, 77, 77, 0.7)"
export const TEXT_LG = "4rem"
export const TEXT_BASE = "2rem"
export const TEXT_SM = "1rem"
export const ICON_SIZE = 35
export const BUTTON_BASE = '4rem'
export const BUTTON_SMALL = '3rem'